dancondo/rails-marketplace

.gitignore, app/models/currency.rb, app/models/post.rb, db/migrate/20180730220727_create_posts.rb, db/migrate/20180730221117_create_currencies.rb, db/migrate/20180730223005_add_currency_to_posts.rb, db/schema.rb, test/models/currency_test.rb, test/models/post_test.rb
Create two models: Post and Currency.  Add a new migration!!  Please check and and if so git pull ... tks
=> Post model

app/controllers/posts_controller.rb, app/views/posts/edit.html.erb, app/views/posts/index.html.erb, app/views/posts/new.html.erb, app/views/posts/show.html.erb, config/routes.rb, test/controllers/posts_controller_test.rb
Dear all ... the posts controller code without the view!  Please, check it out ...
=> create post controller

Gemfile.lock, app/controllers/application_controller.rb, app/models/user.rb, app/views/devise/registrations/new.html.erb, app/views/shared/_navbar.html.erb, app/views/users/show.html.erb
Add user validations including CPF
=> User features

app/assets/stylesheets/components/_banner.scss, app/assets/stylesheets/config/_colors.scss, app/assets/stylesheets/config/_fonts.scss, app/assets/stylesheets/pages/_home.scss, app/views/pages/home.html.erb
Proposta de font e paleta instalada
=> color and fonts fixed

Gemfile, Gemfile.lock, app/controllers/application_controller.rb, app/policies/application_policy.rb, app/policies/post_policy.rb, test/policies/post_policy_test.rb
Add the gem of punit, and generate the policies. However, the logic in the posts still need to be implemented.
=> install pundit and create the general policies and post's policies controller

app/controllers/posts_controller.rb, app/views/posts/_form.html.erb, app/views/posts/index.html.erb, app/views/posts/new.html.erb, app/views/posts/show.html.erb, config/routes.rb, db/seeds.rb
Dear all ... this version is ready to instance a basic seed db and to show first version of posts view
=> instance seed and posts views

app/assets/stylesheets/components/_footer.scss, app/assets/stylesheets/components/_index.scss, app/views/layouts/application.html.erb, app/views/shared/_footer.html.erb
Da uma olhadinha caralhoooooooo, nao esquece de cagar !
=> footer fixed

app/models/order.rb, db/migrate/20180731182847_create_orders.rb, db/schema.rb, test/models/order_test.rb
Felloww, this one only reates the ORDER MODEL, which references to users and posts tables, and also execute the db migration.
=> create order model and db migrate

app/controllers/application_controller.rb, app/controllers/posts_controller.rb, app/policies/post_policy.rb, app/views/layouts/application.html.erb, app/views/pages/home.html.erb, app/views/posts/_form.html.erb, app/views/posts/index.html.erb, db/migrate/20180731174049_remove_coin_from_currencies.rb, db/migrate/20180731174110_add_name_to_currencies.rb, db/schema.rb, db/seeds.rb
=> Update currency table, add container to all pages but home

db/migrate/20180731182847_create_orders.rb
There was a little problem with the last pull request, this one is just to fix the db migration that did not get updated.
=> fix cb-migrate

app/controllers/orders_controller.rb, app/views/orders/create.html.erb, app/views/orders/index.html.erb, app/views/orders/show.html.erb, config/routes.rb, test/controllers/orders_controller_test.rb
Mr. GIGXXXX
This version creates the actions for the Order Controller ... push play!!!
=> create order's controller actions

app/controllers/orders_controller.rb, app/models/order.rb, app/models/post.rb, app/models/user.rb, app/policies/order_policy.rb, app/views/orders/show.html.erb, app/views/posts/show.html.erb, app/views/users/show.html.erb, config/routes.rb, db/migrate/20180801154720_add_status_to_orders.rb, db/schema.rb, test/policies/order_policy_test.rb
Now the orders are live! they change the amount of a post and in case they are canceled they return it back. Besides they have a status that shows if the order was completed or is still pending. 
Don't forget to migrate!
=> Transactions organism

app/assets/stylesheets/components/_form.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_navbar.scss, app/assets/stylesheets/components/_table.scss, app/assets/stylesheets/config/_colors.scss, app/views/posts/_form.html.erb, app/views/posts/index.html.erb, app/views/posts/new.html.erb, app/views/posts/show.html.erb
Implementação da table em /posts/index.html.erb e ajuste do HEX do laranja.
=> Implement table in posts index

db/migrate/20180802141330_remove_ease_from_posts.rb, db/migrate/20180802150134_add_valid_to_posts.rb, db/schema.rb
Pessoal,
Fiz alterações na tabela POSTS:
1 - removi a coluna EASE (ágio);
2 - inseri a coluna valid para termos o tempo de validade do POST
Por favor avaliem ... abs.
=> creat column valid and remove column ease at posts table

app/controllers/posts_controller.rb, app/models/order.rb, db/migrate/20180802151954_remove_valid_from_posts.rb, db/migrate/20180802152049_add_duration_to_posts.rb, db/schema.rb
troquei a coluna valid por duratin no model.
criei a regra no metodo destroy de POSTS para destruir em função do tempo (duration)
=> destroy posts considering the duration

db/migrate/20180802165538_add_price_and_change_amount_to_float_to_posts.rb, db/migrate/20180802165801_remove_ease_from_posts.rb, db/schema.rb
People!!!
Estamos trocando amount para ser o valor FLOAT na cripto a ser vendida.  E inserindo o campo PRICE com o valor em Reais da venda!
=> change amount to float and insert price on posts table

app/views/posts/_form.html.erb, app/views/posts/index.html.erb, app/views/posts/show.html.erb, db/migrate/20180802165801_remove_ease_from_posts.rb, db/schema.rb
Cleaning the code from ease fields!!
=> erasing ease from earth

app/views/posts/index.html.erb
=> first adjustment

app/views/pages/home.html.erb, app/views/users/show.html.erb, db/migrate/20180802190704_change_amount_from_orders.rb, db/schema.rb, db/seeds.rb
New seed file, necessary to generate new migration to work plenty
=> Create a seed.rb file that makes new users orders, posts, and currencies with a fictinal rate

app/assets/stylesheets/components/_table.scss, app/assets/stylesheets/config/_colors.scss, app/assets/stylesheets/config/_fonts.scss, app/assets/stylesheets/pages/_general.scss, app/assets/stylesheets/pages/_index.scss, app/assets/stylesheets/pages/_users.scss, app/views/posts/index.html.erb, app/views/users/show.html.erb
Desenvolvi a user's page, troquei as fontes e já adicionei as variáveis de classe necessárias para a conexão com a API do coinapi.
=> Implement user page

app/assets/stylesheets/pages/_index.scss, app/assets/stylesheets/pages/_view-order.scss, app/views/orders/show.html.erb
=> show order fixed

app/assets/stylesheets/components/_navbar.scss, app/assets/stylesheets/pages/_general.scss, app/views/orders/create.html.erb, app/views/orders/index.html.erb, app/views/posts/_form.html.erb, app/views/posts/edit.html.erb, app/views/posts/index.html.erb, app/views/posts/new.html.erb, app/views/shared/_navbar.html.erb
Fiz pequenas alterações, como o ajuste da cor da navbar e a devida margem no div container do views/posts/index.html.erb
=> Adjust details

app/assets/stylesheets/components/_table.scss, app/assets/stylesheets/pages/_home.scss, app/assets/stylesheets/pages/_view-order.scss, app/views/orders/show.html.erb, app/views/pages/home.html.erb
head of the table // chave de recebimento
=> head of the table // chave de recebimento
